"""Add source and updated_at to terrain_tiles

Revision ID: c61059ced7e4
Revises: 001
Create Date: 2026-08-25 18:42:30.152864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c61059ced7e4'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terrain_tiles', sa.Column('source', sa.String(), nullable=True))
    op.add_column('terrain_tiles', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_terrain_tiles_source'), 'terrain_tiles', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_terrain_tiles_source'), table_name='terrain_tiles')
    op.drop_column('terrain_tiles', 'updated_at')
    op.drop_column('terrain_tiles', 'source')
    # ### end Alembic commands ###
